name = "Optimized Addons"
author = "zapolab"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efc264e90a257326b042954bf60a271083087067d197cf6d1dad59dee2f0ce17"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
