name = "Optimized Addons"
author = "zapolab"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d74507697f21ba01b340c4c620896ea8e125497ebad6c585d44b1e7c44cf632"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
