name = "Optimized Addons"
author = "zapolab"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59a764eb2af0c0b868b8d9b33ccd7e411ace2cdb3bb182715de6cc232bbbc219"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
